"""Company repository port.

Defined as ``typing.Protocol`` — never ABC — so the application layer remains
framework-neutral.
"""

from __future__ import annotations

from typing import Protocol

from app.application.companies.dto import CompanyDTO, CreateCompanyCommand, UpdateCompanyCommand


class CompanyRepository(Protocol):
    def create(self, command: CreateCompanyCommand) -> CompanyDTO: ...
    def get(self, company_id: int) -> CompanyDTO | None: ...
    def update(self, command: UpdateCompanyCommand) -> CompanyDTO: ...
    def list_all(self, skip: int = 0, limit: int = 100) -> list[CompanyDTO]: ...
    def count_all(self) -> int: ...
    def list_for_user(self, user_id: int, skip: int = 0, limit: int = 100) -> list[CompanyDTO]: ...
    def count_for_user(self, user_id: int) -> int: ...
