"""Add company_user_invitations

Revision ID: 017272ca352d
Revises: b50367530b9f
Create Date: 2026-07-02 08:36:09.039006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017272ca352d'
down_revision: Union[str, Sequence[str], None] = 'b50367530b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_user_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_company_user_invitations_company_id'), 'company_user_invitations', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_user_invitations_email'), 'company_user_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_company_user_invitations_id'), 'company_user_invitations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_user_invitations_id'), table_name='company_user_invitations')
    op.drop_index(op.f('ix_company_user_invitations_email'), table_name='company_user_invitations')
    op.drop_index(op.f('ix_company_user_invitations_company_id'), table_name='company_user_invitations')
    op.drop_table('company_user_invitations')
    # ### end Alembic commands ###
