"""Add audit log actor and change fields

Revision ID: 953915c692cb
Revises: 017272ca352d
Create Date: 2026-07-02 09:07:08.254389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953915c692cb'
down_revision: Union[str, Sequence[str], None] = '017272ca352d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('actor_user_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_email', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_name', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('old_values', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('new_values', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'new_values')
    op.drop_column('audit_logs', 'old_values')
    op.drop_column('audit_logs', 'actor_name')
    op.drop_column('audit_logs', 'actor_email')
    op.drop_column('audit_logs', 'actor_user_id')
    # ### end Alembic commands ###
