"""create fiscal years and periods tables

Revision ID: b8401de8334a
Revises: d17a284486bd
Create Date: 2026-05-22 09:55:50.966754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8401de8334a'
down_revision: Union[str, Sequence[str], None] = 'd17a284486bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscal_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'closed', 'locked')", name='ck_fiscal_years_status'),
    sa.CheckConstraint('end_date >= start_date', name='ck_fiscal_years_date_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_fiscal_years_company_name')
    )
    op.create_index(op.f('ix_fiscal_years_company_id'), 'fiscal_years', ['company_id'], unique=False)
    op.create_index(op.f('ix_fiscal_years_id'), 'fiscal_years', ['id'], unique=False)
    op.create_table('fiscal_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('period_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'closed', 'locked')", name='ck_fiscal_periods_status'),
    sa.CheckConstraint('end_date >= start_date', name='ck_fiscal_periods_date_range'),
    sa.CheckConstraint('period_no >= 1 AND period_no <= 12', name='ck_fiscal_periods_period_no'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_year_id', 'name', name='uq_fiscal_periods_year_name'),
    sa.UniqueConstraint('fiscal_year_id', 'period_no', name='uq_fiscal_periods_year_period_no')
    )
    op.create_index(op.f('ix_fiscal_periods_company_id'), 'fiscal_periods', ['company_id'], unique=False)
    op.create_index(op.f('ix_fiscal_periods_fiscal_year_id'), 'fiscal_periods', ['fiscal_year_id'], unique=False)
    op.create_index(op.f('ix_fiscal_periods_id'), 'fiscal_periods', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fiscal_periods_id'), table_name='fiscal_periods')
    op.drop_index(op.f('ix_fiscal_periods_fiscal_year_id'), table_name='fiscal_periods')
    op.drop_index(op.f('ix_fiscal_periods_company_id'), table_name='fiscal_periods')
    op.drop_table('fiscal_periods')
    op.drop_index(op.f('ix_fiscal_years_id'), table_name='fiscal_years')
    op.drop_index(op.f('ix_fiscal_years_company_id'), table_name='fiscal_years')
    op.drop_table('fiscal_years')
    # ### end Alembic commands ###
